/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kosm' at '07.05.17 19:16' with Gradle 3.1
 *
 * @author kosm, @date 07.05.17 19:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
